### ISSUE TITLE
Spring native

### ISSUE THREAD

**Issue by jabrena** [jabrena/101-docker#10]
```
2022-11-02T16:38:04.280Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164) ~[app:3.0.0-RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:578) ~[app:6.0.0-RC2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[app:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[app:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[app:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[app:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[app:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[app:3.0.0-RC1]
	at com.example.benchmarks.BenchmarkServerJibber.main(BenchmarkServerJibber.java:18) ~[app:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:208) ~[app:3.0.0-RC1]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:194) ~[app:3.0.0-RC1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183) ~[app:3.0.0-RC1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[app:3.0.0-RC1]
	... 8 common frames omitted
Caused by: java.nio.file.NoSuchFileException: /tmp/tomcat.8080.1228880437960241164
	at java.base@19/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[app:na]
	at java.base@19/java.nio.file.Files.createDirectory(Files.java:700) ~[na:na]
	at java.base@19/java.nio.file.TempFileHelper.create(TempFileHelper.java:134) ~[na:na]
	at java.base@19/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:171) ~[na:na]
	at java.base@19/java.nio.file.Files.createTempDirectory(Files.java:1017) ~[na:na]
	at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:202) ~[app:3.0.0-RC1]
	... 11 common frames omitted

```

**Comment by jabrena** [comment]
- https://stackoverflow.com/questions/48122371/how-to-create-an-empty-file-in-a-scratch-container

**Comment by jabrena** [comment]
Fixed
